name: CI
on:
  # Triggers the workflow on push event for the current feature branch
  pull_request:
  push:
    # for testing build from specific feature branch:
    # (note: do not forget to modify tag_name and release_name when doing so!)
    # branches: [ feature/build-gui-version ]
    branches: [ release/v0.2.0 ]
    # release tagged versions:
    # tags:
    #  - 'v*' # Push events to matching v*, i.e. v0.1.0, v0.1.1, etc.
jobs:
  createrelease:
    name: Create release
    runs-on: [ubuntu-latest]
    steps:
    - name: Get date & time for release name
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%d_%H-%M-%S')"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        # tag_name: ${{ github.ref }}
        # release_name: Release ${{ github.ref }}
        # use the following two lines for testing/ release candidates (e.g. in combination with a feature branch)
        tag_name: "rc-${{ steps.datetime.outputs.datetime }}"
        release_name: "RC ${{ steps.datetime.outputs.datetime }}"
        draft: true
        prerelease: true
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  build:
    name: Build executables
    runs-on: ${{ matrix.os }}
    needs: createrelease
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            # default shell on Windows seems to be PowerShell (this is also why `rmdir` cannot be used)
            PREPARE_ASSET_CLI: Compress-Archive -Path ./dist/cli -DestinationPath windows_cli.zip
            PREPARE_ASSET_GUI: Compress-Archive -Path ./dist/gui -DestinationPath windows_gui.zip
            OUT_FILE_NAME_CLI: windows_cli.zip
            OUT_FILE_NAME_GUI: windows_gui.zip
            CLEAN_BETWEEN_BUILDS: Remove-Item -Path ./build -Force -Recurse; Remove-Item -Path ./dist -Force -Recurse; Remove-Item -Path ./__pycache__ -Force -Recurse
          - os: ubuntu-latest
            TARGET: ubuntu
            PREPARE_ASSET_CLI: zip -r ubuntu_cli.zip ./dist/cli
            PREPARE_ASSET_GUI: zip -r ubuntu_gui.zip ./dist/gui
            OUT_FILE_NAME_CLI: ubuntu_cli.zip
            OUT_FILE_NAME_GUI: ubuntu_gui.zip
            CLEAN_BETWEEN_BUILDS: rm -rf ./build && rm -rf ./dist && rm -rf __pycache__
          - os: macos-latest
            TARGET: macos
            PREPARE_ASSET_CLI: zip -r macos_cli.zip ./dist/cli
            PREPARE_ASSET_GUI: zip -r macos_gui.zip ./dist/gui
            OUT_FILE_NAME_CLI: macos_cli.zip
            OUT_FILE_NAME_GUI: macos_gui.zip
            CLEAN_BETWEEN_BUILDS: rm -rf ./build && rm -rf ./dist && rm -rf __pycache__
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.*'

      - name: Install dependencies for testing
        run: pip install -r requirements.txt

      # - name: Call the Python script to show its usage
      #  run: python cli.py --help

      - name: Install dependencies for deployment
        run: pip install pyinstaller

      - name: Run PyInstaller on ${{matrix.TARGET}} for creation of executable (GUI)
        run: pyinstaller gui.py

      - name: Prepare asset (GUI)
        run: |
          cp the-hand.png ./dist/gui
          ${{matrix.PREPARE_ASSET_GUI}}

      - name: Load Release URL File from release job
        uses: actions/download-artifact@v1
        with:
          name: release_url

      - name: Get release file name and upload URL
        id: get_release_info
        shell: bash
        run: |
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value

      - name: Upload release asset (GUI)
        id: upload-release-asset-gui
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ${{ matrix.OUT_FILE_NAME_GUI}}
          asset_name: ${{ matrix.OUT_FILE_NAME_GUI}}
          asset_content_type: application/zip

      - name: Run PyInstaller on ${{matrix.TARGET}} for creation of executable (CLI)
        run: |
          ${{matrix.CLEAN_BETWEEN_BUILDS}}
          pyinstaller cli.py

      - name: Prepare asset (CLI)
        run: |
          cp the-hand.png ./dist/cli 
          ${{matrix.PREPARE_ASSET_CLI}}

      - name: Upload release asset (CLI)
        id: upload-release-asset-cli
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ${{ matrix.OUT_FILE_NAME_CLI}}
          asset_name: ${{ matrix.OUT_FILE_NAME_CLI}}
          asset_content_type: application/zip

      - name: Upload CHANGELOG as release asset
        id: upload-release-asset-doc
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: CHANGELOG.md
          asset_name: CHANGELOG.md
          asset_content_type: text/markdown; charset=UTF-8
