name: CI
on:
  # Triggers the workflow on push event for the current feature branch
  pull_request:
  push:
    # for testing build from specific feature branch:
    # (note: do not forget to modify tag_name and release_name when doing so!)
    branches: [ feature/build-gui-version ]
    # release tagges versions:
    # tags:
    #  - 'v*' # Push events to matching v*, i.e. v0.1.0, v0.1.1, etc.
jobs:
  createrelease:
    name: Create release
    runs-on: [ubuntu-latest]
    steps:
    - name: Get date & time for release name
      id: datetime
      run: echo "::set-output name=datetime::$(date +'%Y-%m-%d_%H-%M-%S')"
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        # release_name: Release ${{ github.ref }}
        # use the following two lines for testing/ release candidates (e.g. in combination with a feature branch)
        # tag_name: "rc-${{ steps.datetime.outputs.datetime }}"
        release_name: "RC ${{ steps.datetime.outputs.datetime }}"
        draft: true
        prerelease: true
    - name: Output Release URL File
      run: echo "${{ steps.create_release.outputs.upload_url }}" > release_url.txt
    - name: Save Release URL File for publish
      uses: actions/upload-artifact@v1
      with:
        name: release_url
        path: release_url.txt

  build:
    name: Build executables
    runs-on: ${{ matrix.os }}
    needs: createrelease
    strategy:
      matrix:
        include:
          - os: windows-latest
            TARGET: windows
            # default shell on Windows seems to be PowerShell
            PREPARE_ASSET: Compress-Archive -Path ./dist/gui -DestinationPath ms-teams-hand-detector_windows.zip
            OUT_FILE_NAME: ms-teams-hand-detector_windows.zip
          - os: ubuntu-latest
            TARGET: ubuntu
            PREPARE_ASSET: zip -r ms-teams-hand-detector_ubuntu.zip ./dist/gui
            OUT_FILE_NAME: ms-teams-hand-detector_ubuntu.zip
          - os: macos-latest
            TARGET: macos
            PREPARE_ASSET: zip -r ms-teams-hand-detector_macos.zip ./dist/gui
            OUT_FILE_NAME: ms-teams-hand-detector_macos.zip
    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE, so the job can access it
      - uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: '3.9.*'

      - name: Install dependencies for testing
        run: pip install -r requirements.txt

      # - name: Call the Python script to show its usage
      #  run: python ms_teams_hand_detector.py --help

      - name: Install dependencies for deployment
        run: pip install pyinstaller

      - name: Run PyInstaller on ${{matrix.TARGET}} for creation of executable
        run: pyinstaller gui.py

      - name: Prepare asset
        run: |
          cp the-hand.png ./dist/gui
          ${{matrix.PREPARE_ASSET}}

      - name: Load Release URL File from release job
        uses: actions/download-artifact@v1
        with:
          name: release_url
  
      - name: Get release file name and upload URL
        id: get_release_info
        shell: bash
        run: |
          value=`cat release_url/release_url.txt`
          echo ::set-output name=upload_url::$value

      - name: Upload release asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release_info.outputs.upload_url }}
          asset_path: ${{ matrix.OUT_FILE_NAME}}
          asset_name: ${{ matrix.OUT_FILE_NAME}}
          asset_content_type: application/zip
